# Generated by Django 5.0.1 on 2024-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_data_criacao_tarefas_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_atualizacao_concluida',
            field=models.DateField(blank=True),
        ),
    ]
