# Generated by Django 5.0.1 on 2024-02-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_alter_tarefas_data_atualizacao_concluida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_atualizacao_concluida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
