# Generated by Django 5.0.1 on 2024-02-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_tarefas_data_atualizacao_concluida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='task',
            field=models.TextField(max_length=100),
        ),
    ]
